[package]
name = "my_work"
version = "0.1.0"
authors = ["Faisal-Munir <engr.faisal2018@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
